deployments:
  multiconfig:
    kubernetes_manifest: pod.yml, pod2.yml
    deployment_type: kubernetes
    kubernetes_default_pod: rss-site
    kubernetes_port_mapping: redmine:3000
    subdomain_port_mapping: redmine:3000
    kubernetes_helm_chart: stable/odoo
    kubernetes_helm_parameters: 
      stable/odoo: odooUsername=username,odooPassword=password,postgresql.postgresPassword=secretpassword
