deployments:
  nginx:
    dockerimage: 
      - r.cfcr.io/wisedrette/wisedrette/dockertest:master
      - cloud.canister.io:5000/wisedrette/obscure-name
    docker_registry:
      - server: r.cfcr.io 
        username: wisedrette
        password: $REGISTRY_PASSWORD
      - server: cloud.canister.io:5000
        username: wisedrette
        password: $REGISTRY_PASSWORD_CANISTER
    deployment_type: kubernetes
    use_kubernetes_registry: false
    port_forwarding: 
      - 80:80
      - 3000:80
    subdomain_port_mapping:
      - nginx:3000
