deployments:
  multiconfig:
    kubernetes_manifest: pod.yml, pod2.yml
    deployment_type: kubernetes
    kubernetes_default_pod: rss-site
    kubernetes_port_mapping: redmine:3000
    subdomain_port_mapping: redmine:3000
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
    kubernetes_secrets:
      - generic ssh-key-secret --from-file=ssh-privatekey=/path/to/.ssh/id_rsa --from-file=ssh-publickey=/path/to/.ssh/id_rsa.pub
      - generic db-user-pass --from-file=./username.txt --from-file=./password.txt

