deployments:
  nginx:
    dockerimage: 
      - ghost:${TAG}
      - redis:${TAG}
    deployment_type: kubernetes
    use_kubernetes_registry: false
    port_forwarding: 
      - 80:2368
      - 6379:6379
