deployments:
  multiconfig:
    kubernetes_manifest: secret.yml, pod.yml, pod2.yml
    deployment_type: kubernetes
    kubernetes_default_image: rss-site
    kubernetes_port_mapping: redmine:3000
    subdomain_port_mapping: redmine:3000
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
