apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyLmNmY3IuaW8iOnsidXNlcm5hbWUiOiJ3aXNlZHJldHRlIiwicGFzc3dvcmQiOiJiNGM1YmE2Yzc4NDc1MmU2YmFmYzc5NDU3NzU2YTgzOCIsImF1dGgiOiJkMmx6WldSeVpYUjBaVHBpTkdNMVltRTJZemM0TkRjMU1tVTJZbUZtWXpjNU5EVTNOelUyWVRnek9BPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: myregistrykey
type: kubernetes.io/dockerconfigjson
